In [1]:
import numpy as np

## numpy array

In [3]:
#Python'daki liste kavramı ile neredeyse aynıdır.
#Matris şeklinde diziler oluşturulabilir.

In [4]:
benimListem = [20,30,40]

In [5]:
type(benimListem)

list

In [6]:
np.array(benimListem) #Bu şekilde yazarak listemizi numpy dizisine çevirebiliriz.

array([20, 30, 40])

In [7]:
type(np.array(benimListem))

numpy.ndarray

In [8]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [9]:
type(matrixListesi)

list

In [10]:
matrixListesi[1][0]

20

In [11]:
np.array(matrixListesi)
#Liste içinde liste olan bir değişkeni numpy dizisine çevirdiğimizde onu matrise çevirir.
#Aslında liste ile pek farkı yok ama görünüm açısından güzel olduğu için çevirebiliriz.
#Bu numpy dizileri devamlı karşımıza çıkacak.
#İlla ki bunu listeden türeteceğiz diye bir şey yok.
#Listelerdeki "range" fonksiyonundan bir liste oluşturduğumuz gibi numpy için de kendi fonksiyonunu kullanacağız.
#Onun adı da "arange" olacak.

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [12]:
np.arange(0,10) #(0,10) arasında dizi oluştur demektir.(10 hariç)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2) #İkişer atlatarak diziyi oluştur demektir. (10 hariç)

array([0, 2, 4, 6, 8])

## zeros

In [38]:
np.zeros(5) #5 tane yanyana 0 oluştur demektir. (5x1 deseydik 5 sütun olacaktı.)

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [42]:
np.zeros((2,2)) #İki parantez kullanarak 2x2'lik 0 matrisi oluştur demektir.

array([[0., 0.],
       [0., 0.]])

## ones

In [16]:
np.ones(5) #5 tane 1 oluştur demektir. (5x1 deseydik 5 sütun olacaktı.)

array([1., 1., 1., 1., 1.])

In [45]:
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [17]:
np.ones((9,9)) #Çift parantez ile 9x9'luk 1 matrisi oluştur demektir.

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [18]:
np.linspace(0,20,5) #(0,20) arasında "eşit mesafede" 5 elemanlı dizi oluştur demektir. (20 dahil)

array([ 0.,  5., 10., 15., 20.])

In [19]:
np.linspace(0,20,6) #(0,20) arasında "eşit mesafede" 6 elemanlı dizi oluştur demektir. (20 dahil)

array([ 0.,  4.,  8., 12., 16., 20.])

In [20]:
np.linspace(0,10,20) #(0,10) arasında "eşit mesafede" 20 elemanlı dizi oluştur demektir. (10 dahil)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
np.linspace(0,5) #Eleman sayısı belirtmediğimizde "eşit aralıklı" 50 elemanlı dizi oluşturur. (5 dahil)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

## eye

In [26]:
np.eye(3) #3x3'lük "birim matris" oluştur demektir.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [2]:
np.random.randn(5)
#Buradaki random, Python'ın değil Numpy'ın kendi kütüphanesinde yer alır.
#"randn" ise içerisine yazılan değer kadar "0 ortalamalı 1 varyanslı" bir dizi oluştur anlamına gelir.
#5x1 deseydin 5 sütun olacaktı.

array([ 0.61476412, -0.16913517,  0.78955122, -1.76539885, -0.48091414])

In [36]:
np.random.randn(4,4) #4x4'lük rastgele oluşturulmuş "0 ortalamalı 1 varyanslı" bir dizi.

array([[ 1.00214782,  1.0150822 ,  1.41444589, -0.98244976],
       [ 1.02648374,  1.23466788,  0.2323962 , -0.28002922],
       [ 0.41791727, -1.01906733,  0.15363016, -0.55280392],
       [ 0.09332426, -0.11479915, -1.36492528, -0.52278131]])

In [31]:
np.random.randint(1,10) #(1,10) arasında rastgele bir tane "tamsayı" oluştur demektir. (10 hariç)

6

In [50]:
np.random.randint(1,10,5) #(1,10) arasında 5 elemanlı rastgele tamsayılar oluştur demektir.

array([3, 7, 8, 2, 4])

In [51]:
benimNumpyDizim = np.arange(30)

In [52]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
benimRandomDizim = np.random.randint(0,100,20)

In [56]:
benimRandomDizim

array([13, 16, 58,  7, 31, 39, 20, 78, 59, 15, 90, 13, 90, 56, 14, 51, 82,
       40, 32, 52])

## numpy dizi metodları

In [58]:
benimNumpyDizim.reshape(5,6)
#30 elemanlı dizimi 5x6'lık matrise çevirdi. (5x6 --> 5 satır 6 sütun)
#Matris boyutları eleman sayısı ile uyumlu olmalı. Örneğin 4x3 olmaz.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
benimNumpyDizim.max()

29

In [60]:
benimRandomDizim.max()

90

In [61]:
benimRandomDizim.min()

7

In [62]:
benimRandomDizim.argmax() #Maksimum değerimin kaçıncı "indexte" olduğunu gösterir.

10

In [63]:
benimRandomDizim.argmin()

3

In [64]:
benimNumpyDizim.shape
#Satır-sütun sayısını gösterir. Fakat reshape halini göstermedi. Biz değişkenimizi reshape fonksiyonu ile değiştirmiştik.

(30,)

In [65]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [66]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [67]:
#Herhangi bir değişkene aktarmadığımız için "benimNumpyDizim" değişkeni hala eski formatında.

In [68]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [69]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [70]:
reshapeDizim.shape #Değişkene aktarıldığından sorun düzeldi.

(5, 6)