In [4]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5] #Numpy dizilerinde indexteki eleman çağırma işlemi listelerdeki ile aynı.

5

In [7]:
benimDizim[3:8] #Slicing işlemi dizilerde de çalışıyor. (8.index hariç)

array([3, 4, 5, 6, 7])

In [8]:
benimDizim[3:8] = -5 #(3,8) arasındaki değerleri -5 yap demektir.

In [9]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi = np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
slicingDizisi = baskaDizi[4:9] #(4:9) arasındaki değeri başka değişkene aktardık.

In [14]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [15]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
slicingDizisi = 700 #Bütün elemanlar 700 olsun istedik.

In [17]:
slicingDizisi 

700

In [18]:
type(slicingDizisi)

int

In [ ]:
#Ama tek değer olarak döndü. Halbuki biz bunu istemiyoruz. Bunu düzeltmenin yolu:

In [19]:
slicingDizisi = baskaDizi[4:9]

In [20]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [21]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
type(slicingDizisi)

numpy.ndarray

In [23]:
slicingDizisi[:]

array([4, 5, 6, 7, 8])

In [24]:
slicingDizisi[:] = 700

In [25]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [26]:
#Sorun düzeldi.

In [27]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [28]:
#baskaDizi değişkenindeki (4,9) aralığındaki indexler de 700 oldu. Çok ilginç!!
#Demek ki oluşturulan "slicingDizisi", "baska dizi" ile bağlantılı. (yeni bir değişken oluşturulsa bile)
#Yani biz bir dizimizdeki belli bir aralığı alıp onu bir değişkene atayıp sonrasında onun değerlerini değiştirirsek
#ilk dizimizin değerleri de değişmiş oluyor.

In [29]:
#Fakat biz orijinal dizideki değerler değişmesin istiyoruz. Bunun için:

In [30]:
ornekDizi = np.arange(0,24)

In [31]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
ornekDiziKopyasi = ornekDizi.copy() #Dizinin kopyasını oluşturup orada işlem yapmak gerekiyor.

In [33]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [36]:
ornekDiziKopyaSlicing[:] = 800

In [37]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [38]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [39]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [5]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [6]:
benimMatrixDizim = np.array(benimListem)

In [7]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [8]:
benimMatrixDizim[0]

array([10, 20, 30])

In [9]:
benimMatrixDizim[1][2] #İndex olarak düşünmek unutulmamalıdır. (1. indexin 2. indexteki elemanı getir demek.)

40

In [10]:
benimMatrixDizim[1,2] #benimMatrixDizim[1][2] ile aynı işlevi görür.

40

In [12]:
benimMatrixDizim[1:,2] #1. indexten sonrasını komple al ve onların 2. indexteki elemanlarını getir demek.

array([40, 60])

In [47]:
benimMatrixDizim[2:,2] #2. indexten sonrasını komple al ve onların 2. indexteki elemanlarını getir demek. (Zaten 1 tane.)

array([60])

In [48]:
benimMatrixDizim[0:,2] #0. indexten sonrasını komple al ve onların 2. indexteki elemanlarını getir demek.

array([30, 40, 60])

In [49]:
benimMatrixDizim[2:,1:] #Böyle de istediğimiz çağırma işlemi yapabiliriz.

array([[50, 60]])

In [50]:
benimMatrixDizim[2:,0:]

array([[40, 50, 60]])

In [51]:
benimMatrixDizim[2:,2:]

array([[60]])

In [54]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [57]:
yeniMatrix = np.array(yeniListe)

In [60]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [62]:
yeniMatrix[[0,2,4]] #0, 2 ve 4. indexteki elemanları liste olarak getir demek.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [63]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [67]:
yeniBirDizi = np.random.randint(1,100,20)

In [68]:
yeniBirDizi

array([56, 89, 62, 26, 30, 69, 17,  9, 65, 86, 93, 14, 73, 85, 45, 80, 28,
       89, 83, 70])

In [69]:
yeniBirDizi > 24 #Dizideki 24'ten büyükleri Boolean olarak döndürdü.

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [70]:
yeniBirDizi

array([56, 89, 62, 26, 30, 69, 17,  9, 65, 86, 93, 14, 73, 85, 45, 80, 28,
       89, 83, 70])

In [71]:
sonucDizisi = yeniBirDizi > 24

In [72]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [73]:
yeniBirDizi

array([56, 89, 62, 26, 30, 69, 17,  9, 65, 86, 93, 14, 73, 85, 45, 80, 28,
       89, 83, 70])

In [74]:
yeniBirDizi[sonucDizisi] #24'ten büyük değerleri göster demek. (Yukarıda o şekilde yaptık.)

array([56, 89, 62, 26, 30, 69, 65, 86, 93, 73, 85, 45, 80, 28, 89, 83, 70])

In [75]:
yeniBirDizi

array([56, 89, 62, 26, 30, 69, 17,  9, 65, 86, 93, 14, 73, 85, 45, 80, 28,
       89, 83, 70])

In [76]:
yeniBirDizi[yeniBirDizi > 24] #Bu şekilde de kolaylıkla yapılabilir.

array([56, 89, 62, 26, 30, 69, 65, 86, 93, 73, 85, 45, 80, 28, 89, 83, 70])

In [77]:
sonDizi = np.arange(0,24)

In [78]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [79]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [80]:
sonDizi #sonDizi değişmedi.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [81]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [82]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [83]:
sonDizi / sonDizi

<ipython-input-83-20a5ae775714>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
#İlk eleman 0 olduğunda 0/0 olmadığında uyarı mesajı ve orayı "nan" olarak yazdırdı.

In [85]:
np.sqrt(sonDizi) #Dizinin karekökünü aldı.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [86]:
np.max(sonDizi)
#sonDizi.max()

23

In [87]:
np.min(sonDizi)
#sonDizi.min()

0